"""rename department

Revision ID: 66438aaeff81
Revises: a53f9f4be4b2
Create Date: 2024-04-03 12:31:56.052344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66438aaeff81'
down_revision = 'a53f9f4be4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department','departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments','department')
   
    # ### end Alembic commands ###
